#This script plots a 40 * 40 field generated by ECA Rule 110 with random initial conditions.

import two_state
from matplotlib import pyplot as plt

initial_condition = two_state.random_string(40)
field = two_state.spacetime_field(110,initial_condition,40)
two_state.spacetime_diagram(field)
plt.show()